export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_MACHINES_SUCCESS = "GET_MACHINES_SUCCESS";
export const GET_MACHINES_FAIL = "GET_MACHINES_FAIL";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const DELETE_MACHINE_SUCCESS = "DELETE_MACHINE_SUCCESS";
export const DELETE_MACHINE_FAIL = "DELETE_MACHINE_FAIL";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const CREATE_MACHINE_SUCCESS = "CREATE_MACHINE_SUCCESS";
export const CREATE_MACHINE_FAIL = "CREATE_MACHINE_FAIL";

export const NEW_REQUEST = "NEW_REQUEST";
export const FINISH_REQUEST = "FINISH_REQUEST";
